package it.auties.protobuf.schema.model;

/**
 * Specifies how a protobuf message or group is represented as a Java type.
 */
public enum TypeForm {
    /**
     * A concrete final class with private fields, a constructor,
     * and {@code @ProtobufAccessor} methods.
     */
    CLASS,

    /**
     * A Java record with annotated record components.
     */
    RECORD,

    /**
     * A Java interface with abstract getter methods annotated
     * with {@code @ProtobufProperty}. An implementation class
     * is generated by the annotation processor.
     */
    INTERFACE,

    /**
     * A sealed abstract class with a single permitted subtype.
     */
    SEALED_CLASS,

    /**
     * A sealed interface with a single permitted record subtype.
     */
    SEALED_INTERFACE
}
